### ISSUE TITLE
Feature Request: Optional specification of the interface for the CURL call

### ISSUE THREAD

**Issue by MichaelKirgus** [Stefomat/dynamic-dns-netcup-api#6]
If the container is used in several instances and is also used in a Kubernetes cluster, it is helpful to use your own host network in order to be able to split the data traffic on the router side over different lines.
Unfortunately, the default route for the curl call is always on the 1st interface. However, it is not possible to influence the 1st interface in all applications (e.g. TrueNAS Scale).
Due to NAT, this then causes problems when applying firewall rules (policy-based routing).
An environment variable like "CURL_INTERFACE" would be great, curl itself supports specifying a source interface using --interface.

**Comment by Stefomat** [comment]
I have experimentally added the environment variable CURL_IFACE. Please use it to see if you can select the curl interface. You can download the image as tag :devel.

**Comment by Stefomat** [comment]
If this works, it should be proposed upstream as a feature, then the script does not need to be adapted here.

**Comment by MichaelKirgus** [comment]
No...but i found another way to implement it. I had to modify the default route settings via docker. Thanks!
